spring.application.name=projet-management

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/stage_db?stringtype=unspecified
spring.datasource.username=stage_user
spring.datasource.password=stage_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}